// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v3.21.12
// source: gossip.proto

package gossip

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// GossipMessage represents a single gossip message.
type GossipMessage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SenderIp      string                 `protobuf:"bytes,1,opt,name=sender_ip,json=senderIp,proto3" json:"sender_ip,omitempty"`       // The IP Address of sender
	ReceiverIp    string                 `protobuf:"bytes,2,opt,name=receiver_ip,json=receiverIp,proto3" json:"receiver_ip,omitempty"` // The IP Address of sender
	Content       string                 `protobuf:"bytes,3,opt,name=content,proto3" json:"content,omitempty"`                         // The actual message content.
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GossipMessage) Reset() {
	*x = GossipMessage{}
	mi := &file_gossip_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GossipMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GossipMessage) ProtoMessage() {}

func (x *GossipMessage) ProtoReflect() protoreflect.Message {
	mi := &file_gossip_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GossipMessage.ProtoReflect.Descriptor instead.
func (*GossipMessage) Descriptor() ([]byte, []int) {
	return file_gossip_proto_rawDescGZIP(), []int{0}
}

func (x *GossipMessage) GetSenderIp() string {
	if x != nil {
		return x.SenderIp
	}
	return ""
}

func (x *GossipMessage) GetReceiverIp() string {
	if x != nil {
		return x.ReceiverIp
	}
	return ""
}

func (x *GossipMessage) GetContent() string {
	if x != nil {
		return x.Content + "-" + x.SenderIp + "->" + x.ReceiverIp
	}
	return ""
}

var File_gossip_proto protoreflect.FileDescriptor

const file_gossip_proto_rawDesc = "" +
	"\n" +
	"\fgossip.proto\x12\x06gossip\"g\n" +
	"\rGossipMessage\x12\x1b\n" +
	"\tsender_ip\x18\x01 \x01(\tR\bsenderIp\x12\x1f\n" +
	"\vreceiver_ip\x18\x02 \x01(\tR\n" +
	"receiverIp\x12\x18\n" +
	"\acontent\x18\x03 \x01(\tR\acontent2Q\n" +
	"\rGossipService\x12@\n" +
	"\fGossipStream\x12\x15.gossip.GossipMessage\x1a\x15.gossip.GossipMessage(\x010\x01B!Z\x1fgrpc_gossip_simulator_fv/gossipb\x06proto3"

var (
	file_gossip_proto_rawDescOnce sync.Once
	file_gossip_proto_rawDescData []byte
)

func file_gossip_proto_rawDescGZIP() []byte {
	file_gossip_proto_rawDescOnce.Do(func() {
		file_gossip_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_gossip_proto_rawDesc), len(file_gossip_proto_rawDesc)))
	})
	return file_gossip_proto_rawDescData
}

var file_gossip_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_gossip_proto_goTypes = []any{
	(*GossipMessage)(nil), // 0: gossip.GossipMessage
}
var file_gossip_proto_depIdxs = []int32{
	0, // 0: gossip.GossipService.GossipStream:input_type -> gossip.GossipMessage
	0, // 1: gossip.GossipService.GossipStream:output_type -> gossip.GossipMessage
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_gossip_proto_init() }
func file_gossip_proto_init() {
	if File_gossip_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_gossip_proto_rawDesc), len(file_gossip_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_gossip_proto_goTypes,
		DependencyIndexes: file_gossip_proto_depIdxs,
		MessageInfos:      file_gossip_proto_msgTypes,
	}.Build()
	File_gossip_proto = out.File
	file_gossip_proto_goTypes = nil
	file_gossip_proto_depIdxs = nil
}
